## Where the samples will be written
save_data: ../exp_data/100_example

## Where the vocab(s) will be written
src_vocab: ../exp_data/100_example/100_example.vocab.src
tgt_vocab: ../exp_data/100_example/100_example.vocab.tgt

# Prevent overwriting existing files in the folder
overwrite: true

# Corpus opts:
data:
    train:
        path_src: ../exp_data/train_100_source.txt
        path_tgt: ../exp_data/train_100_target.txt
    valid:
        path_src: ../exp_data/dev_source.txt
        path_tgt: ../exp_data/dev_target.txt
...
